version: "3"

services:
  backend:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 3333:3333
    volumes:
      - ./backend:/app/backend
  frontend:
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 3000:3000
      - 80:3000
    volumes:
      - ./frontend:/app/frontend